Added check for armature modifier.
readyplayerme/rpm-blender-validator pull request #3
Opened 2023-07-05 18:54 UTC by TechyDaniel

feat: Added check for armature modifier.
fix: added that check in the configs.
renamed the configs to be in sync with other teams

2023-07-05 18:55 UTC, TechyDaniel commented
https://ready-player-me.atlassian.net/browse/TECHART-60

2023-07-07 10:36 UTC, Olaf-Wolf3D requested changes

2023-07-07 10:36 UTC, Olaf-Wolf3D commented on rpm_pyblish_plugins/validate_mesh_armature.py
> +            )
We should raise an error instead of logging. Using f-string in logs is discouraged for security reasons.

2023-07-07 10:36 UTC, Olaf-Wolf3D commented on rpm_pyblish_plugins/validate_mesh_armature.py
> +        )
We should also check that the modifier's target is set and not None.

2023-07-11 07:18 UTC, TechyDaniel commented on rpm_pyblish_plugins/validate_mesh_armature.py
> +        )
aha, so the modifier target should always be Armature. got it. will add it.

2023-07-11 13:36 UTC, Olaf-Wolf3D reviewed
Please bump versions of plugins.

2023-07-11 13:37 UTC, Olaf-Wolf3D approved these changes

2023-07-11 13:41 UTC, merged